### PR TITLE
Change search response

### PR DESCRIPTION
**Pull request by Samorai**
Changing search logic 
1. Searching by mobile phone only
2. First mobile phone to 'person short' response (Temporary solution)
3. Added more fields to response
Approved by @AlekzandrV  into Slack conversation

### CODE REVIEW

**Comment by Samorai** [comment]
Hey guys! PR was sent 14 hours ago, review it plz. It's blocker for Dima.
@AndrewDryga @gmile @PavelVesnin

**Comment by gmile** [comment]
@Samorai @ivchenkodima apologies for blocking the work. This is now merged

**Comment by PavelVesnin** [comment]
@gmile you're so fast :) I just open my notebook and PR is merged

**Comment by gmile** [comment]
@PavelVesnin teamwork! :)

**Comment by Samorai** [comment]
Thanks :)

**Pull request merged**
